### ISSUE TITLE
No config file for urxvt

### ISSUE THREAD

**Issue by dazai-osamu-san** [VaughnValle/kofuku#4]

**Comment by Z3W** [comment]
https://wiki.archlinux.org/index.php/rxvt-unicode#Configuration

https://github.com/VaughnValle/kofuku/blob/master/.Xresources

**Comment by Whylde-Tech** [comment]
Not to speak for the author.  However, most of the time urxvt pulls it's config from the Xresources file.

**Comment by dazai-osamu-san** [comment]
ok thanks
