### ISSUE TITLE
WHERE IS GRUB CONFIG!!! PLEASEEEEEEEE

### ISSUE THREAD

**Issue by P4NAD3ROXIS** [VaughnValle/kofuku#5]
I love your grub config & the boot screen how i can have it

**Comment by VaughnValle** [comment]
Hi! I use rEFInd for my bootscreen. I lost the dotfiles unfortunately, but it's relatively easy to setup. Here are some useful resource

rEFInd: https://wiki.archlinux.org/index.php/REFInd
rEFInd theme: https://github.com/EvanPurkhiser/rEFInd-minimal

**Comment by VaughnValle** [comment]
If you'd like some help, feel free to contact me over Discord 8bitrosso#9754 :) Closing this issue
